name: build
on: workflow_dispatch

jobs:
  os:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Build docker images
      run: make rpi
